[package]
name = "quro"
description = "A command-line query runner for multiple databases."
authors = ["Konstantin Zhigaylo <kostyazero@proton.me>"]
repository = "https://github.com/kostya-zero/quro"
homepage = "https://github.com/kostya-zero/quro"
keywords = ["database", "cli", "sql"]
readme = "README.md"
license = "MIT"
version = "0.5.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
colored = "3.1.1"
dir_spec = "0.5.2"
native-tls = { version = "0.2.18", features = ["vendored"] }
postgres = "0.19.14"
postgres-native-tls = "0.5.3"
rusqlite = { version = "0.40.2", features = ["bundled"] }
rustyline = "18.0.1"
serde = { version = "1.0.229", features = ["derive"] }
tabled = { version = "0.22.0", features = ["ansi"] }
thiserror = "2.0.21"
toml = "1.1.6"

[profile.dev]
opt-level = 1
debug = "line-tables-only"

[profile.dev.package."*"]
opt-level = 2
debug = false

[profile.release]
panic = "abort"
opt-level = 3
lto = "fat"
strip = true
