[package]
name = "quro"
description = "A CLI query runner with support for multiple databases."
authors = ["Konstantin Zhigaylo <kostyazero@proton.me>"]
repository = "https://github.com/kostya-zero/quro"
homepage = "https://github.com/kostya-zero/quro"
keywords = ["database", "cli", "sql"]
readme = "README.md"
license = "MIT"
version = "0.4.2"
edition = "2024"

[profile.dev]
debug = "line-tables-only"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.4", features = ["derive"] }
colored = "3.1.1"
postgres = "0.19.14"
postgres-native-tls = "0.5.2"
native-tls = { version = "0.2.18", features = ["vendored"] }
rusqlite = { version = "0.40.1", features = ["bundled"] }
rustyline = "18.0.1"
tabled = { version = "0.22.0", features = ["ansi"] }
thiserror = "2.0.19"

[profile.release]
panic = "abort"
opt-level = 3
codegen-units = 1
incremental = false
lto = "thin"
debug = 0
strip = true
